### ISSUE TITLE
 Error during setup of component circadian_lighting

### ISSUE THREAD

**Issue by TIMSCHMITZ** [claytonjn/hass-circadian_lighting#122]
After adding circadian_lighting to my configuration.yaml
`switch:
  - platform: circadian_lighting
    lights_xy:
      - light.0x680ae2fffe161079_light
`
i recive the error in my main log:
`2020-09-27 20:32:53 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-27 20:32:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-27 20:33:01 ERROR (MainThread) [homeassistant.setup] Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 92, in setup
    conf = config[DOMAIN]
KeyError: 'circadian_lighting'`

my light got the following properties:
`
light.0x680ae2fffe161079_light | on | brightness: 149 hs_color: 0, 0.392 rgb_color: 255, 254, 254 xy_color: 0.324, 0.329 update_available: false state: ON color:  x: 0.323 'y': 0.329  friendly_name: Birne_light supported_features: 57
-- | -- | --
`

**Comment by dobh** [comment]
I had the same problem after installing it via HACS. I needed to add empty `circadian_lighting:` into **configuration.yaml** and then it worked.

```
<..>
circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_xy:
    - light.0x680ae2fffe161079_light
<..>
```

**Comment by basnijholt** [comment]
You are doing it wrong. 

You need 
platform: switch

**Comment by vguttmann** [comment]
If this resolved your issue, please consider closing this issue.

**Comment by lachmanfrantisek** [comment]
I've hit the same error. This hack helped but I wouldn't consider that as a fix...;)
