### ISSUE TITLE
Unable to prepare setup for platform circadian_lighting.switch: Unable to set up component.

### ISSUE THREAD

**Issue by AdamHughes** [claytonjn/hass-circadian_lighting#130]
This is from the log file of Home Assistant 0.118.4 using Carcadian Lighting 1.0.13

I clicked the install though HACS and then restarted Home Assistant. 

```
2020-11-27 13:52:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-27 13:52:41 ERROR (MainThread) [homeassistant.setup] Error during setup of component circadian_lighting
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/homeassistant/.homeassistant/custom_components/circadian_lighting/__init__.py", line 92, in setup
conf = config[DOMAIN]
KeyError: 'circadian_lighting'
2020-11-27 13:52:41 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform circadian_lighting.switch: Unable to set up component.
```

**Comment by claytonjn** [comment]
What do the relevant lines of your configuration.yaml look like?

**Comment by AdamHughes** [comment]
> What do the relevant lines of your configuration.yaml look like?

This is my entire configuration.yaml file:
I only have 2 bulbs connected to HA at the moment. One is light.main and the other light.lamp

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


tuya_custom:
  devices_config:
    - device_name: Lamp # this is mandatory with at least one of the other keys
      support_color: true # true or false, force color support for device
      brightness_range_mode: 0 # 0 = use brightness range 10-1000
                               # 1 = use brightness range 1-255
      min_kelvin: 1000 # min val = 2700 - define minumum kelvin temp accepted by the light
      max_kelvin: 10000 # max val = 6500 - define maximum kelvin temp accepted by the light
      max_tuya_temp: 10000 # min val = 10000 - define the maximum color temp reported by the light
                           # to ajust lovelace color temp slider range
    - device_name: Room Light # this is mandatory with at least one of the other keys
      support_color: true # true or false, force color support for device
      brightness_range_mode: 0 # 0 = use brightness range 10-1000
                               # 1 = use brightness range 1-255
      min_kelvin: 2700 # min val = 2700 - define minumum kelvin temp accepted by the light
      max_kelvin: 6500 # max val = 6500 - define maximum kelvin temp accepted by the light
      max_tuya_temp: 10000 # min val = 10000 - define the maximum color temp reported by the light
                           # to ajust lovelace color temp slider range

switch:
  - platform: circadian_lighting
    lights_rgb:
      - light.main
      - light.lamp

```

**Comment by claytonjn** [comment]
You need to add at least `circadian_lighting:` at the top level (same level as `switch:`, `scene:`, etc.)

**Comment by AdamHughes** [comment]
Ah, many thanks. It seems to be working perfectly now! Thanks again
