### ISSUE TITLE
crash on module load

### ISSUE THREAD

**Issue by BrainDamage** [claytonjn/hass-circadian_lighting#133]
```
Source: custom_components/circadian_lighting/__init__.py:174
First occurred: 01:28:42 (1 occurrences)
Last logged: 01:28:42
Error during setup of component circadian_lighting

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/hass/custom_components/circadian_lighting/__init__.py", line 109, in setup
    cl = CircadianLighting(hass, min_colortemp, max_colortemp,
  File "/var/lib/hass/custom_components/circadian_lighting/__init__.py", line 139, in __init__
    self.data['percent'] = self.calc_percent()
  File "/var/lib/hass/custom_components/circadian_lighting/__init__.py", line 210, in calc_percent
    today_sun_times = self.get_sunrise_sunset(now)
  File "/var/lib/hass/custom_components/circadian_lighting/__init__.py", line 174, in get_sunrise_sunset
    location = astral.Location()
AttributeError: module 'astral' has no attribute 'Location'
```
indeed if I try to python -c 'import astral; astral.Location()' I get the same error, and checking the documentation, there's no such method available
astral version here is 2.2
taking a peek at the doc it seems there's a [location.Location()](https://astral.readthedocs.io/en/latest/package.html#astral-location) method, perhaps it changed along the versions?

**Comment by basnijholt** [comment]
You have the incorrect version installed, see this https://github.com/home-assistant/core/blob/13cdf0ba6310c92758a858405dab60ad371e8a46/requirements.txt#L5

**Comment by BrainDamage** [comment]
Interesting, thanks, I guess my distro package is to blame since it has a hard dep on the latest version; strangely no other functionality broke despite using sun-based patterns myself
