### ISSUE TITLE
Circadian Lighting no longer functioning with 2021.12.1 (HTTP 400 Bad Request)

### ISSUE THREAD

**Issue by ThomasPrior** [claytonjn/hass-circadian_lighting#181]
Config:

```
circadian_lighting:
  min_colortemp: 1500
  max_colortemp: 5000
  sunset_offset: -00:45:00
```
What's happening:

Nothing. Turning on CL does not change lighting in any way.

Expected behaviour:

Turning on CL should adjust the brightness and temperature

Logs:

```
Logger: homeassistant.core
Source: components/hue/bridge.py:132
First occurred: 14:52:57 (1 occurrences)
Last logged: 14:52:57

Error executing service: <ServiceCall light.turn_on (c:530fd1f35fbfc30ee59a6232aabd6251): entity_id=['light.living_room'], params=transition=60.0, brightness=254, color_temp=514>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 494, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/group.py", line 175, in async_turn_on
    await self.bridge.async_request_call(
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 132, in async_request_call
    return await task(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/lights.py", line 85, in set_state
    await self._send_put(id, update_obj)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/base.py", line 137, in _send_put
    await self._bridge.request("put", endpoint, json=data)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 152, in request
    async with self.create_request(method, path, **kwargs) as resp:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 182, in create_request
    res.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://ip_of_hue_bridge/clip/v2/resource/light/70cc3873-0e31-4772-a457-2a127b282383')
```

System info:

## System Health

version | core-2021.12.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Europe/London

**Comment by ThomasPrior** [comment]
https://github.com/home-assistant/core/issues/61679#issuecomment-992431630 seems to indicate the colortemp values are out of range, but adjusting the values as per that post gives the following config error:

```
Invalid config for [circadian_lighting]: value must be at least 1000 for dictionary value @ data['circadian_lighting']['max_colortemp']. Got 500 value must be at least 1000 for dictionary value @ data['circadian_lighting']['min_colortemp']. Got 153. (See /config/configuration.yaml, line 13).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 170, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [circadian_lighting]: value must be at least 1000 for dictionary value @ data['circadian_lighting']['max_colortemp']. Got 500
value must be at least 1000 for dictionary value @ data['circadian_lighting']['min_colortemp']. Got 153. (See /config/configuration.yaml, line 13). 

```

**Comment by swallace17** [comment]
I am experiencing a similar issue, running Home Assistant 2021.12.6. Every time I enable Circadian Lighting, I am met with the following error. 

```
Logger: homeassistant.core
Source: components/hue/bridge.py:117 
First occurred: 2:00:38 AM (12 occurrences) 
Last logged: 2:00:50 AM

Error executing service: <ServiceCall light.turn_on (c:2eb0f35bf9fb8d3229d3d15a8d78e3e3): entity_id=['light.kitchen_recessed_5'], params=transition=1.0, brightness=82, color_temp=1000>
Error executing service: <ServiceCall light.turn_on (c:6b0ab352b75697f7b54a5c42f642de93): entity_id=['light.kitchen_recessee_6'], params=transition=1.0, brightness=82, color_temp=1000>
Error executing service: <ServiceCall light.turn_on (c:205df8368a382578742fcda2e433ccaa): entity_id=['light.kitchen_recessed_3'], params=transition=1.0, brightness=82, color_temp=1000>
Error executing service: <ServiceCall light.turn_on (c:b81802b79e3e28cbc4fa9b157ebf9f71): entity_id=['light.kitchen_sink'], params=transition=1.0, brightness=82, color_temp=1000>
Error executing service: <ServiceCall light.turn_on (c:be6cebc512bdeda63d177045f119bd64): entity_id=['light.kitchen_recessed_7'], params=transition=1.0, brightness=82, color_temp=1000>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 494, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/light.py", line 165, in async_turn_on
    await self.bridge.async_request_call(
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 117, in async_request_call
    return await task(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/lights.py", line 80, in set_state
    await self.update(id, update_obj)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/base.py", line 146, in update
    await self._bridge.request("put", endpoint, json=data)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 182, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://10.0.200.154/clip/v2/resource/light/c47f9d2c-23c3-4b26-8a5d-68d367cc79cd')
```

**Comment by swallace17** [comment]
Did a bit more digging. Setup CL to only adjust a single light to simplify the logs, and also enabled debug logging on everything related to CL. Logs are as follows: 

```
[36m2021-12-28 02:24:29 DEBUG (MainThread) [custom_components.circadian_lighting.switch] Scheduling 'light.turn_on' with the following 'service_data': {'entity_id': 'light.kitchen_recessed_3', 'transition': 1.0, 'brightness': 86, 'color_temp': 1000}[0m
[31m2021-12-28 02:24:29 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall light.turn_on (c:0f3feff7771d1bd924fea73094273146): entity_id=['light.kitchen_recessed_3'], params=transition=1.0, brightness=86, color_temp=1000>

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
await coro_or_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 494, in async_handle_light_on_service
await light.async_turn_on(**filter_turn_on_params(light, params))
File "/usr/src/homeassistant/homeassistant/components/hue/v2/light.py", line 165, in async_turn_on
await self.bridge.async_request_call(
File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 117, in async_request_call
return await task(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/lights.py", line 80, in set_state
await self.update(id, update_obj)
File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/base.py", line 146, in update
await self._bridge.request("put", endpoint, json=data)
File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 182, in request
resp.raise_for_status()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://10.0.200.154/clip/v2/resource/light/b7954c22-e413-4bb8-860a-88dcc7fa0559')[0m
```

**Comment by swallace17** [comment]
I just managed to solve this by commenting out the following in my circadian_lighting: config from configuration.yaml. I set this all up many many versions again and had not touched it, not sure what broke. Suspecting minimum values is messing it up. Going to keep testing and will update. 

circadian_lighting:
  interval: 600
  #max_colortemp: 10000
  #min_colortemp: 1000
  #sunset_offset: 00:00:00

**Comment by claytonjn** [comment]
Hey, sorry I missed this due to the holidays. The min_colortemp range in the documentation is correct - from a technical perspective CL can send values in that range. That does not mean, however, that your actual bulbs can accept values in that range. The errors you're seeing are coming from the Hue integration, not from CL; basically, it seems that because you configured CL to try setting values outside of the range Hue can accept it is now throwing errors (most Hue bulbs have a range of ~2500-6500).

The Hue integration got a huge overhaul with 2021.12.x, switching from v1 Hue API to v2. I believe that with the v1 API if a colortemp value was requested outside of the available range it would default to the closest reproducible value (i.e. if a bulb has a range of 2500-6500 and you try to set 1000 it actually set to 2500). It appears with the v2 API it now throws a 400 error if the value is outside the available range. 

Ultimately this isn't a problem with CL or with HA, but a change in the Hue API behavior. The fix would be to set a range that your bulbs can actually produce.
