### ISSUE TITLE
Not working with Home Assistant 2022.2

### ISSUE THREAD

**Issue by kidcoma** [claytonjn/hass-circadian_lighting#186]
Hi, my Circadian Lighting stopped working with 2022.2 - it works fine if I roll back to a 2021.12 version of HA. I tried updating my HA instance again today (2022.2.5) and the same thing. I even tried uninstalling and reinstalling Circadian Lighting in HACS (also removed and re-added the lines in the Config file). Not sure if it matters, but the lights I'm using it with are running Tasmota.

**Comment by vangguppie** [comment]
Up one here. 

Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 107, in setup
    conf = config[DOMAIN]
KeyError: 'circadian_lighting'

**Comment by vguttmann** [comment]
I had the same problem with 2022.10.2, but as mentioned in #122 , I simply had to add the empty key `circadian_lighting:` to my config.yaml, and now it works like a charm.
