### ISSUE TITLE
HA 2022.4: Error during setup of component circadian_lighting

### ISSUE THREAD

**Issue by jlatvala** [claytonjn/hass-circadian_lighting#188]
Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/config/custom_components/circadian_lighting/__init__.py", line 204, in _get_sun_events
    location = astral.location.Location()
AttributeError: module 'astral' has no attribute 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 108, in setup
    hass.data[DOMAIN] = CircadianLighting(
  File "/config/custom_components/circadian_lighting/__init__.py", line 157, in __init__
    self._percent = self.calc_percent()
  File "/config/custom_components/circadian_lighting/__init__.py", line 260, in calc_percent
    today = self._relevant_events(now)
  File "/config/custom_components/circadian_lighting/__init__.py", line 251, in _relevant_events
    sun_events = self._get_sun_events(now + timedelta(days=days))
  File "/config/custom_components/circadian_lighting/__init__.py", line 206, in _get_sun_events
    location = astral.Location()
AttributeError: module 'astral' has no attribute 'Location'

**Comment by jlatvala** [comment]
This error is not visible in logs after the first boot after upgrading HA, but if you reboot again, then you see the error

**Comment by claytonjn** [comment]
2.0.8-beta includes the change from @mdieperink that may fix this issue, have you tried installing that version of Circadian Lighting?

**Comment by jlatvala** [comment]
2.0.8-beta seems to work
