### ISSUE TITLE
Error's out during the period of minight sun.

### ISSUE THREAD

**Issue by steino** [claytonjn/hass-circadian_lighting#32]
Simply put, the sun does not set here for a period during summer causing this to error out. 

Mon Jul 08 2019 00:03:49 GMT+0200 (Central European Summer Time)
Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/home/steino/venv/homeassistant/lib/python3.6/site-packages/astral.py", line 1891, in sunrise_utc
    return self._calc_time(90 + 0.833, SUN_RISING, date, latitude, longitude, observer_elevation)
  File "/home/steino/venv/homeassistant/lib/python3.6/site-packages/astral.py", line 2747, in _calc_time
    hourangle = self._hour_angle(latitude, solarDec, depression + adjustment)
  File "/home/steino/venv/homeassistant/lib/python3.6/site-packages/astral.py", line 2723, in _hour_angle
    HA = acos(h)
ValueError: math domain error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steino/venv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/steino/.homeassistant/custom_components/circadian_lighting/__init__.py", line 112, in setup
    interval, transition)
  File "/home/steino/.homeassistant/custom_components/circadian_lighting/__init__.py", line 138, in __init__
    self.data['percent'] = self.calc_percent()
  File "/home/steino/.homeassistant/custom_components/circadian_lighting/__init__.py", line 205, in calc_percent
    today_sun_times = self.get_sunrise_sunset(now)
  File "/home/steino/.homeassistant/custom_components/circadian_lighting/__init__.py", line 179, in get_sunrise_sunset
    sunrise = location.sunrise(date)
  File "/home/steino/venv/homeassistant/lib/python3.6/site-packages/astral.py", line 871, in sunrise
    sunrise = self.astral.sunrise_utc(date, self.latitude, self.longitude, elevation)
  File "/home/steino/venv/homeassistant/lib/python3.6/site-packages/astral.py", line 1895, in sunrise_utc
    ("Sun never reaches the horizon on this day, " "at this location.")
astral.AstralError: Sun never reaches the horizon on this day, at this location.

**Comment by claytonjn** [comment]
Hmm, this is an interesting problem. I have no idea how to calculate values if the sun never sets on a particular day; I would need to know what the lowest position the sun reaches is and at what time it is at that position, however I don't see any Python libraries that would provide that information. I suppose I could just have CL set values to `max_colortemp` and `max_brightness` the entire day if no sunset time is available. 

Any thoughts/suggestions?

**Comment by steino** [comment]
According to https://astral.readthedocs.io/en/latest/ it can calculate solar noon and solar midnight. Could this be used for this calculation?

**Comment by claytonjn** [comment]
I'm already using both of those - there's essentially four data points and four parabolas calculated (solar noon and solar midnight might not be half way between sunrise and sunset):
![68747470733a2f2f636f6d6d756e6974792d686f6d652d617373697374616e742d6173736574732e73332e6475616c737461636b2e75732d776573742d322e616d617a6f6e6177732e636f6d2f6f726967696e616c2f33582f362f352f36353766663938626562](https://user-images.githubusercontent.com/3850252/61012525-f54fcb00-a34c-11e9-8c52-7a16d59805ba.png)

I suppose what I could do if the sun never rises or never sets a particular day is use solar noon and solar midnight as the amplitudes of a sinusoidal graph. In the case of the sun never rising, the graph would be shifted down by the difference between the highest it ever gets and the horizon (would cause lights to dim from `max_bightness` minus that difference to `min_brightness` back to `max_brightness` minus difference). In the case of the sun never setting, the graph would be shifted up by the difference between the lowest if ever gets and the horizon (would cause lights to change from `min_colortemp` plus that difference to `max_colortemp` back to `min_colortemp` + difference).
